# Generated by Django 4.2.23 on 2025-07-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="donor", name="last_donation_date",),
    ]
