# Generated by Django 4.2.23 on 2025-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0002_remove_donor_last_donation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="password",
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
    ]
