# Generated by Django 4.2.23 on 2025-07-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0003_donor_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="donor_indentity",
            field=models.CharField(default=1234, max_length=15),
            preserve_default=False,
        ),
    ]
