# Generated by Django 4.2.23 on 2025-07-05 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0004_donor_donor_indentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donation_id", models.CharField(max_length=20, unique=True)),
                (
                    "amount_donated",
                    models.PositiveIntegerField(
                        help_text="Amount in milliliters (300-500ml)",
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("blood_type", models.CharField(max_length=3)),
                ("hospital_name", models.CharField(max_length=100)),
                ("donation_date", models.DateField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="donor.donor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Donation",
                "verbose_name_plural": "Blood Donations",
                "ordering": ["-donation_date"],
            },
        ),
    ]
