# Generated by Django 4.2.23 on 2025-07-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0005_donation"),
    ]

    operations = [
        migrations.RemoveField(model_name="donation", name="is_verified",),
    ]
