# Generated by Django 4.2.23 on 2025-07-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0006_remove_donation_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation", name="donation_date", field=models.DateField(),
        ),
    ]
