# Generated by Django 4.2.23 on 2025-07-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0007_alter_donation_donation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="city",
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
