# Generated by Django 4.2.23 on 2025-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0008_donation_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donation_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="donor",
            name="donor_indentity",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
