# Generated by Django 4.2.23 on 2025-07-06 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0009_alter_donation_donation_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity in milliliters",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("hospital_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
