# Generated by Django 4.2.23 on 2025-07-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0010_bloodstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("blood_group", models.CharField(max_length=3)),
                ("date_of_birth", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
