# Generated by Django 4.2.23 on 2025-07-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0011_receiver"),
    ]

    operations = [
        migrations.RemoveField(model_name="receiver", name="created_at",),
    ]
