# Generated by Django 4.2.23 on 2025-07-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0013_bloodrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="donor.receiver"
            ),
        ),
    ]
