# Generated by Django 4.2.23 on 2025-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0014_alter_bloodrequest_requester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodstock",
            name="blood_type",
            field=models.CharField(max_length=3),
        ),
    ]
